# Generated by Django 5.1 on 2024-09-12 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rentals', '0004_worker_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
    ]
