# Generated by Django 5.1 on 2024-09-14 21:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rentals', '0006_relocationrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveNotice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('planned_leave_date', models.DateField()),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('notice_date', models.DateTimeField(auto_now_add=True)),
                ('decision_date', models.DateTimeField(blank=True, null=True)),
                ('refund_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Rentals.house')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Rentals.tenant')),
            ],
        ),
    ]
