# Generated by Django 5.1 on 2024-09-15 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rentals', '0007_leavenotice'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='house_number',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='house',
            name='is_vacant',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterUniqueTogether(
            name='house',
            unique_together={('name', 'house_number')},
        ),
    ]
