# Generated by Django 5.1.2 on 2024-10-30 17:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rentals', '0011_house_booking_amount_house_is_booked'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Rentals.payment_year'),
        ),
    ]
