# Generated by Django 5.1.2 on 2024-10-30 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Rentals', '0013_alter_payment_year'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ['year', 'month', 'tenant']},
        ),
        migrations.AlterUniqueTogether(
            name='payment',
            unique_together={('tenant', 'month', 'year')},
        ),
    ]
