# Generated by Django 5.1.2 on 2024-11-01 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rentals', '0014_alter_payment_options_alter_payment_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenants_database',
            name='date_paid',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tenants_database',
            name='gender',
            field=models.CharField(blank=True, default='N/A', max_length=100, null=True),
        ),
    ]
