# Generated by Django 5.1.2 on 2024-11-01 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Rentals', '0015_tenants_database_date_paid_tenants_database_gender'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tenants_database',
            old_name='date_paid',
            new_name='dob',
        ),
    ]
